
birthday1 = input("when is John's birthday?")
print("John's birthday is",birthday1, ".")
birthday2 = input("when is Meera's birthday?")
print("Meera's birthday is",birthday2, ".")
birthday3 = input("when is David's birthday?")
print("David's birthday is",birthday3, ".")
birthday4 = input("when is Maria's birthday?")
print("Maria's birthday is",birthday4, ".")
birthday5 = input("when is your birthday?")
print("Your birthday is",birthday5, ".")